### ISSUE TITLE
Availability as WebAssembly

### ISSUE THREAD

**Issue by shayc** [google/project-gameface#22]
I don't know if it's easy/hard or possible, but it would be awesome if this was available for the browser as a WebAssembly module.

This project is rocks!

**Comment by RodriSanchez1** [comment]
![image](https://github.com/google/project-gameface/assets/80465873/428c4e35-558d-49b5-b72f-bc1d2fdb442e)

[https://handsfreejs.netlify.app/]( https://handsfreejs.netlify.app/)
 
 @sheyc
