### ISSUE TITLE
Does this support mac or web?

### ISSUE THREAD

**Issue by Skypow2012** [google/project-gameface#44]
I want to use this to control the page in web

**Comment by s1newaves** [comment]
Probably web, but only on windows and Android. Its literally in the readme.

**Comment by Skypow2012** [comment]
It would be very convenient if could support web or mac pages.

**Comment by s1newaves** [comment]
It is in python. Maybe you can try running it?

**Comment by willwade** [comment]
Re #2 #9 and I’m sure others. #42 

basically it needs reworking a few libraries. It’s doable. I can’t see us doing it in  our fork as the inbuilt MacOS camera gesture is pretty good already and we are targeting windows heavily with a better upgrade and installation process . But Linux for sure it has a role.
